#! /bin/sh
##start-stop script for MyRents Api daemon
EXEC=/usr/bin/php5 
PIDFILE=/var/run/mailerd.pid
OPTS=/srv/www/myrents/protected/yiic.php\ mailerd

set -e
. /lib/lsb/init-functions
test -x $EXEC || exit 0
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        log_daemon_msg "Starting Myrents Mailer Daemon" "mailerd"

        if start-stop-daemon --start --quiet --oknodo --make-pidfile --background --pidfile $PIDFILE --exec $EXEC -- $OPTS; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;

  stop)
        log_daemon_msg "Stopping Myrents Mailer Daemon" "mailerd"

        if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;

  restart)
        log_daemon_msg "Restarting Myrents Mailer Daemon" "mailerd"
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE

        if start-stop-daemon --start --quiet --oknodo --make-pidfile --background --pidfile $PIDFILE --exec $EXEC -- $OPTS; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  status)
        status_of_proc -p $PIDFILE $EXEC apid && exit 0 || exit $?
        ;;
  *)
        log_action_msg "Usage: /etc/init.d/mailerd {start|stop|restart|status}"
        exit 1
esac

exit 0
