<?php
return array(
	'odessa' => 'Одесса',
	'kiev' => 'Киев',
	'dnepropetrovsk' => 'Днепропетровск',
	'donetsk' => 'Донецк',
	'lviv' => 'Львов',
	'kharkiv' => 'Харьков',
	'nikolaev' => 'Николаев',
	'kherson'=>'Херсон',
	'simferopol'=>'Симферополь',
	'uzhgorod'=>'Ужгород',
	'lutsk'=>'Луцк',
	'ivano-frankovsk'=>'Ивано-Франковск',
	'rovno'=>'Ровно',
	'ternopol'=>'Тернополь',
	'chernivtsi'=>'Черновцы',
	'khmelnitsky'=>'Хмельницкий',
	'chernihiv'=>'Чернигов',
	'cherkasy'=>'Черкассы',
	'poltava'=>'Полтава',
	'lugansk'=>'Луганск',
	'kirovograd'=>'Кировоград',
	'zaporozhye'=>'Запорожье',
	'sumy'=>'Сумы',
	'vinnytsia'=>'Винница',
	'zhitomir'=>'Житомир',
	
    );
